# -*- coding: utf-8 -*-
"""Bert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12XgaHQuZb5Y3wNlIM3G0qm1e_5ZH77x1
"""

import spacy
import json
import requests
import pprint
#!python -m spacy download en_core_web_trf

class preproces:
  def __init__(self, text):
    self.text = text
    pass
  
  def passer(self, text, list1, list2, label):
    text = text.lower()
    # flag = 1
    txt = set(text.split())
    
    if label not in ['PERSON', 'ORG']:
      return False
    
    ls1 = set()
    for i in list1:
      for j in i.split():
        ls1.add(j.lower())
    ls2 = set()
    for i in list2:
      for j in i.split():
        ls1.add(j.lower())
    print(txt,ls1,ls2, label)
    for i in txt:
      if i in ls1:
        return False
      if i in ls2:
        return False
    return True

  def call(self):
    nlp = spacy.load("en_core_web_sm")
    # text =  """ alicia is a 23 year old white female presents with complaint of allergies.  She used to have allergies when she lived in Seattle but she thinks they are worse here.  In the past, she has tried Claritin, and Zyrtec.  Both worked for short time but then seemed to lose effectiveness.  She has used allegra also.  She used that last summer and she began using it again two weeks ago.  It does not appear to be working very well.  She has used over-the-counter sprays but no prescription nasal sprays.  She does have asthma but doest not require daily medication for this and does not think it is flaring up.,MEDICATIONS: , Her only medication currently is orthotricyclen and the allegra.,ALLERGIES: , She has no known medicine allergies.,OBJECTIVE:,Vitals:  Weight was 130 pounds and blood pressure 124/78. ,HEENT:  Her throat was mildly erythematous without exudate.  Nasal mucosa was erythematous and swollen.  Only clear drainage was seen.  TMs were clear.,Neck:  Supple without adenopathy.,Lungs:  Clear.,ASSESSMENT:,  Allergic rhinitis.,PLAN:,1.  She will try Zyrtec instead of allegra again.  Another option will be to use loratadine.  She does not think she has prescription coverage so that might be cheaper.,2.  Samples of Nasonex two sprays in each nostril given for three weeks.  A prescription was written as well."""
    text = self.text
    doc = nlp(text)

    d = requests.post(url="https://bern.korea.ac.kr/plain", data={'sample_text': text}).json()
    pp = pprint.PrettyPrinter(indent=4)
    pp.pprint(d)
    print('--------------------------------------------------------')
    pp.pprint(doc)

    diseases = []
    drugs = []
    persons = []
    date = []
    quantity = []
    for a in d['denotations']:
      if a['obj']=='disease':
        diseases.append(text[a['span']['begin']:a['span']['end']])
      if a['obj']=='drug':
        drugs.append(text[a['span']['begin']:a['span']['end']])

    for ent in doc.ents:
      if self.passer(ent.text, diseases, drugs, ent.label_):
        persons.append(ent.text)
      if ent.label_ == 'DATE':
        date.append(ent.text)
      if ent.label_ == 'QUANTITY':
        quantity.append(ent.text)

    results = dict()
    results['diseases'] = tuple(diseases)
    results['drugs'] = tuple(drugs)
    results['persons'] = tuple(persons)
    results["date"] = tuple(date)
    results['quantity'] = tuple(quantity)
    return results



